name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@main
        with:
          mdbook-version: "latest"
      - name: Generate SUMMARY.md
        run: ./scripts/gen-summary.sh
      - name: Build with mdBook
        run: mdbook build
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./book
